# Generated by Django 4.1.5 on 2023-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=70, unique=True, verbose_name="Email"),
        ),
    ]
